name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  boolean_validation:
    path: ../
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

permittedLicenses:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - MIT
  - MIT-Modern-Variant
  - MPL-2.0
  - Zlib

packageLicenseOverride:
  flutter: BSD-3-Clause
  flutter_driver: BSD-3-Clause
  flutter_goldens: BSD-3-Clause
  flutter_localizations: BSD-3-Clause
  flutter_web_plugins: BSD-3-Clause
  flutter_test: BSD-3-Clause
  fuchsia_remote_debug_protocol: BSD-3-Clause
  integration_test: BSD-3-Clause
  rxdart: Apache-2.0