name: boolean_validation
description: "A comprehensive validation package for Dart and Flutter applications, providing utilities to validate various data types such as names, email addresses, URLs, mobile numbers, and more. It ensures that user inputs are accurate and conform to specified formats, making it easier to handle user data securely and effectively."
version: 0.1.0
homepage: https://github.com/2Math0/boolean_validation
repository: https://github.com/2Math0/boolean_validation
issues_tracker: https://github.com/2Math0/boolean_validation/issues
keywords:
  - validation
  - dart
  - flutter
documentation: https://2Math0.github.io/boolean_validation
example: https://github.com/2Math0/boolean_validation/example

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

permittedLicenses:
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'MIT-Modern-Variant'
  - 'MPL-2.0'
  - 'Zlib'

packageLicenseOverride:
  flutter: 'BSD-3-Clause'
  flutter_driver: 'BSD-3-Clause'
  flutter_goldens: 'BSD-3-Clause'
  flutter_localizations: 'BSD-3-Clause'
  flutter_web_plugins: 'BSD-3-Clause'
  flutter_test: 'BSD-3-Clause'
  fuchsia_remote_debug_protocol: 'BSD-3-Clause'
  integration_test: 'BSD-3-Clause'
  rxdart: 'Apache-2.0'
