import 'package:boolean_validation/boolean_validation.dart';

/// Represents mobile number validation config for a country
enum CountryPhonePattern {
  usa('US', '1', 'United States', MobileRegex.usaRegex),
  canada('CA', '1', 'Canada', MobileRegex.canadaRegex),
  india('IN', '91', 'India', MobileRegex.indiaRegex),
  uk('UK', '44', 'United Kingdom', MobileRegex.ukRegex),
  france('FR', '33', 'France', MobileRegex.franceRegex),
  germany('DE', '49', 'Germany', MobileRegex.germanyRegex),
  italy('IT', '39', 'Italy', MobileRegex.italyRegex),
  brazil('BR', '55', 'Brazil', MobileRegex.brazilRegex),
  mexico('MX', '52', 'Mexico', MobileRegex.mexicoRegex),
  china('CN', '86', 'China', MobileRegex.chinaRegex),
  japan('JP', '81', 'Japan', MobileRegex.japanRegex),
  australia('AU', '61', 'Australia', MobileRegex.australiaRegex),
  southAfrica('ZA', '27', 'South Africa', MobileRegex.southAfricaRegex),
  russia('RU', '7', 'Russia', MobileRegex.russiaRegex),
  turkey('TR', '90', 'Turkey', MobileRegex.turkeyRegex),
  pakistan('PK', '92', 'Pakistan', MobileRegex.pakistanRegex),
  indonesia('ID', '62', 'Indonesia', MobileRegex.indonesiaRegex),

  // Arabic Countries
  egypt('EG', '20', 'Egypt', MobileRegex.egyptRegex),
  saudiArabia('SA', '966', 'Saudi Arabia', MobileRegex.saudiArabiaRegex),
  algeria('DZ', '213', 'Algeria', MobileRegex.algeriaRegex),
  bahrain('BH', '973', 'Bahrain', MobileRegex.bahrainRegex),
  comoros('KM', '269', 'Comoros', MobileRegex.comorosRegex),
  djibouti('DJ', '253', 'Djibouti', MobileRegex.djiboutiRegex),
  iraq('IQ', '964', 'Iraq', MobileRegex.iraqRegex),
  jordan('JO', '962', 'Jordan', MobileRegex.jordanRegex),
  kuwait('KW', '965', 'Kuwait', MobileRegex.kuwaitRegex),
  lebanon('LB', '961', 'Lebanon', MobileRegex.lebanonRegex),
  libya('LY', '218', 'Libya', MobileRegex.libyaRegex),
  mauritania('MR', '222', 'Mauritania', MobileRegex.mauritaniaRegex),
  morocco('MA', '212', 'Morocco', MobileRegex.moroccoRegex),
  oman('OM', '968', 'Oman', MobileRegex.omanRegex),
  palestine('PS', '970', 'Palestine', MobileRegex.palestineRegex),
  qatar('QA', '974', 'Qatar', MobileRegex.qatarRegex),
  somalia('SO', '252', 'Somalia', MobileRegex.somaliaRegex),
  sudan('SD', '249', 'Sudan', MobileRegex.sudanRegex),
  syria('SY', '963', 'Syria', MobileRegex.syriaRegex),
  tunisia('TN', '216', 'Tunisia', MobileRegex.tunisiaRegex),
  uae('AE', '971', 'United Arab Emirates', MobileRegex.uaeRegex),
  yemen('YE', '967', 'Yemen', MobileRegex.yemenRegex),
  ;

  const CountryPhonePattern(this.isoCode, this.dialCode, this.name, this.regex);

  final String isoCode;
  final String dialCode;
  final String name;
  final String regex;

  /// O(1), compile-time, fully traceable, keys in Country Two-letters
  static const Map<String, CountryPhonePattern> byIsoCode = {
    'US': usa,
    'CA': canada,
    'IN': india,
    'UK': uk,
    'FR': france,
    'DE': germany,
    'IT': italy,
    'BR': brazil,
    'MX': mexico,
    'CN': china,
    'JP': japan,
    'AU': australia,
    'ZA': southAfrica,
    'RU': russia,
    'TR': turkey,
    'PK': pakistan,
    'ID': indonesia,

    // Arabic Countries ISO Codes
    'EG': egypt,
    'SA': saudiArabia,
    'DZ': algeria,
    'BH': bahrain,
    'KM': comoros,
    'DJ': djibouti,
    'IQ': iraq,
    'JO': jordan,
    'KW': kuwait,
    'LB': lebanon,
    'LY': libya,
    'MR': mauritania,
    'MA': morocco,
    'OM': oman,
    'PS': palestine,
    'QA': qatar,
    'SO': somalia,
    'SD': sudan,
    'SY': syria,
    'TN': tunisia,
    'AE': uae,
    'YE': yemen,
  };

  /// O(1), compile-time, fully traceable, keys in country codes
  static const Map<String, CountryPhonePattern> byDialCode = {
    '1': usa,
    '91': india,
    '44': uk,
    '33': france,
    '49': germany,
    '39': italy,
    '55': brazil,
    '52': mexico,
    '86': china,
    '81': japan,
    '61': australia,
    '27': southAfrica,
    '7': russia,
    '90': turkey,
    '92': pakistan,
    '62': indonesia,

    // Arabic Countries Dial Codes
    '20': egypt,
    '966': saudiArabia,
    '213': algeria,
    '973': bahrain,
    '269': comoros,
    '253': djibouti,
    '964': iraq,
    '962': jordan,
    '965': kuwait,
    '961': lebanon,
    '218': libya,
    '222': mauritania,
    '212': morocco,
    '968': oman,
    '970': palestine,
    '974': qatar,
    '252': somalia,
    '249': sudan,
    '963': syria,
    '216': tunisia,
    '971': uae,
    '967': yemen,
  };
}
