name: Deploy boolean_validation Example Web app to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy_example_web.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Clean Flutter build cache
        run: flutter clean
        working-directory: example

      - name: Get dependencies for example
        run: flutter pub get
        working-directory: example

      - name: Generate localization files
        run: flutter gen-l10n
        working-directory: example

      - name: Build example web release
        run: flutter build web --release
        working-directory: example

      - name: Fix base href for GitHub Pages
        run: |
          sed -i 's#<base href="/">#<base href="/boolean_validation/">#g' example/build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: example/build/web
